//

#pragma once

namespace send_headers_login
{
	constexpr short kLoginStatus = 0x00;
	constexpr short kSERVER_STATUS = 0x03;
	constexpr short kPIN_CHECK_OPERATION = 0x06;
	constexpr short kSERVER_LIST = 0x0a;
	constexpr short kCHARACTER_LIST = 0x0b;
	constexpr short kSERVER_IP = 0x0c;
	constexpr short kCHECK_CHARACTER_NAME = 0x0d;
	constexpr short kCREATE_NEW_CHARACTER = 0x0e;
	constexpr short kDELETE_CHARACTER = 0x0f;
	constexpr short kCHANGE_CHANNEL = 0x10;
	constexpr short kCHANNEL_SELECTED = 0x14;
	constexpr short kRELOG_RESPONSE = 0x16;
}

namespace send_headers
{
	constexpr short kMODIFY_INVENTORY_ITEM = 0x1D;
	constexpr short kUPDATE_STATS = 0x1F;
	constexpr short kGIVE_BUFF = 0x20;
	constexpr short kCANCEL_BUFF = 0x1E; // wrong
	constexpr short kUPDATE_SKILLS = 0x21; // wrong
	constexpr short kFAME = 0x26;
	constexpr short kSHOW_STATUS_INFO = 0x27;
	constexpr short kSHOW_QUEST_COMPLETION = 0x31;
	constexpr short kREQUEST_HIRED_MERCHANT = 0x32;
	constexpr short kUSE_SKILL_BOOK = 0x33;
	constexpr short kGUILD_BBS_OPERATION = 0x3B;
	constexpr short kCHAR_INFO = 0x3D;
	constexpr short kPARTY_OPERATION = 0x3E;
	constexpr short kBUDDY_LIST = 0x3F;
	constexpr short kGUILD_OPERATION = 0x41;
	constexpr short kSPAWN_PORTAL = 0x43;
	constexpr short kSERVERMESSAGE = 0x44;
	constexpr short kYELLOW_TIP = 0x4A; // wrong
	constexpr short kSHOW_AVATAR_MEGA = 0x6F; // untested
	constexpr short kWARP_TO_MAP = 0x7D;
	constexpr short kOPEN_CASHSHOP = 0x7F;
	constexpr short kMULTICHAT = 0x86;
	constexpr short kWHISPER = 0x87;
	constexpr short kMAP_EFFECT = 0x68; // wrong
	constexpr short kCLOCK = 0x6E; // wrong
	constexpr short kBOAT_EFFECT = 0x6F; // wrong
	constexpr short kSPAWN_PLAYER = 0xA0;
	constexpr short kREMOVE_PLAYER_FROM_MAP = 0xA1;
	constexpr short kCHATTEXT = 0x7A; // wrong
	constexpr short kCHALKBOARD = 0xA4;
	constexpr short kSHOW_SCROLL_EFFECT = 0xA7;
	constexpr short kPET_SPAWN = 0xA8;
	constexpr short kPET_MOVE = 0xAA;
	constexpr short kPET_CHAT = 0x82; // wrong
	constexpr short kPET_NAMECHANGE = 0x83; // wrong
	constexpr short kPET_COMMAND = 0x85; // wrong
	constexpr short kSUMMON_SPAWN = 0xAF;
	constexpr short kSUMMON_REMOVE = 0xB0;
	constexpr short kSUMMON_MOVE = 0xB1;
	constexpr short kSUMMON_ATTACK = 0x89; // wrong
	constexpr short kDAMAGE_SUMMON = 0x8A; // wrong
	constexpr short kMOVE_PLAYER = 0xB9;
	constexpr short kCLOSE_RANGE_ATTACK = 0xBA;
	constexpr short kRANGED_ATTACK = 0x8F; // wrong
	constexpr short kMAGIC_ATTACK = 0x90; // wrong
	constexpr short kENERGY_ATTACK = 0x91; // wrong
	constexpr short kSKILL_EFFECT = 0x92; // wrong
	constexpr short kCANCEL_SKILL_EFFECT = 0x93; // wrong
	constexpr short kDAMAGE_PLAYER = 0x94; // wrong
	constexpr short kFACIAL_EXPRESSION = 0x95; // wrong
	constexpr short kSHOW_ITEM_EFFECT = 0x96; // wrong
	constexpr short kSHOW_CHAIR = 0x97; // wrong
	constexpr short kUPDATE_CHAR_LOOK = 0x98; // wrong
	constexpr short kSHOW_FOREIGN_EFFECT = 0x99; // wrong
	constexpr short kGIVE_FOREIGN_BUFF = 0x9A; // wrong
	constexpr short kCANCEL_FOREIGN_BUFF = 0x9B; // wrong
	constexpr short kUPDATE_PARTYMEMBER_HP = 0x9C; // wrong
	constexpr short kCANCEL_CHAIR = 0xA0; // wrong
	constexpr short kSHOW_ITEM_GAIN_INCHAT = 0xA1; // wrong
	constexpr short kUPDATE_QUEST_INFO = 0xA6; // wrong
	constexpr short kCOOLDOWN = 0xAD; // wrong
	constexpr short kSPAWN_MONSTER = 0xAF; // wrong
	constexpr short kKILL_MONSTER = 0xB0; // wrong
	constexpr short kSPAWN_MONSTER_CONTROL = 0xB1; // wrong
	constexpr short kMOVE_MONSTER = 0xB2; // wrong
	constexpr short kMOVE_MONSTER_RESPONSE = 0xB3; // wrong
	constexpr short kDAMAGE_MONSTER = 0xB9; // wrong
	constexpr short kSHOW_MONSTER_HP = 0xBD; // wrong
	constexpr short kSPAWN_NPC = 0xC2; // wrong
	constexpr short kSPAWN_NPC_REQUEST_CONTROLLER = 0xC4; // wrong
	constexpr short kSPAWN_HIRED_MERCHANT = 0xCA; // wrong
	constexpr short kDESTROY_HIRED_MERCHANT = 0xCB; // wrong
	constexpr short kDROP_ITEM_FROM_MAPOBJECT = 0xCD; // wrong
	constexpr short kREMOVE_ITEM_FROM_MAP = 0xCE; // wrong
	constexpr short kSPAWN_MIST = 0xD2; // wrong
	constexpr short kREMOVE_MIST = 0xD3; // wrong
	constexpr short kSPAWN_DOOR = 0xD4; // wrong
	constexpr short kREMOVE_DOOR = 0xD5; // wrong
	constexpr short kREACTOR_HIT = 0xD6; // wrong
	constexpr short kREACTOR_SPAWN = 0xD8; // wrong
	constexpr short kREACTOR_DESTROY = 0xD9; // wrong
	constexpr short kMONSTER_CARNIVAL_START = 0xE2; // wrong
	constexpr short kMONSTER_CARNIVAL_OBTAINED_CP = 0xE3; // wrong
	constexpr short kMONSTER_CARNIVAL_PARTY_CP = 0xE4; // wrong
	constexpr short kMONSTER_CARNIVAL_SUMMON = 0xE5; // wrong
	constexpr short kMONSTER_CARNIVAL_MESSAGE = 0xE6; // wrong
	constexpr short kMONSTER_CARNIVAL_DIED = 0xE7; // wrong
	constexpr short kMONSTER_CARNIVAL_LEAVE = 0xE8; // wrong
	constexpr short kMONSTER_CARNIVAL_SHOW_GAME_RESULT = 0xE9; // wrong
	constexpr short kNPC_TALK = 0xED; // wrong
	constexpr short kOPEN_NPC_SHOP = 0xEE; // wrong
	constexpr short kCONFIRM_SHOP_TRANSACTION = 0xEF; // wrong
	constexpr short kOPEN_STORAGE = 0xF0; // wrong
	constexpr short kFREDRICK_MESSAGE = 0xF1; // wrong
	constexpr short kFREDRICK_OPERATION = 0xF2; // wrong
	constexpr short kMESSENGER = 0xF4; // wrong
	constexpr short kPLAYER_INTERACTION = 0xF5; // wrong
	constexpr short kSHOW_CASH = 0xFF; // wrong
	constexpr short kCASHSHOP_OPERATION = 0x100; // wrong
	constexpr short kKEYMAP = 0x107; // wrong
}
